name: gaussian_splatting
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - plyfile=0.8.1
  - pytorch=2.0.0
  - pytorch-cuda=11.8
  - torchaudio=2.0.0
  - torchvision=0.15.0
  - tqdm
  - pip:
    - submodules/diff-gaussian-rasterization
    - submodules/simple-knn